version: "3"
services:
  migration-server:
    image: ramesesinc/db-migration-server:0.0.1
    container_name: db-migration-server
    restart: always
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: 10m
    ports:
      - "5000:5000"
    environment:
      TZ: "Asia/Manila"
    env_file:
      - ./_custom/env.conf
    volumes:
      - /home/rameses/dbm-root/waterworks/migrations:/dbm-root/waterworks/migrations
    